import type { Metadata } from "next";
import Link from "next/link";
import { LegalList } from "@/components/legal/LegalList";
import { LegalPageLayout } from "@/components/legal/LegalPageLayout";
import { LegalSection, LegalSubheading } from "@/components/legal/LegalSection";
import { legalConfig, legalMailto } from "@/config/legal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${legalConfig.brandName}.`,
  alternates: {
    canonical: "/terms",
  },
  openGraph: {
    title: `Terms of Service | ${legalConfig.brandName}`,
    description: `Terms of Service for ${legalConfig.brandName}.`,
    url: "/terms",
    siteName: legalConfig.brandName,
    type: "website",
  },
};

export default function TermsPage() {
  const brand = legalConfig.brandName;

  return (
    <LegalPageLayout
      title="Terms of Service"
      dateLabel="Last updated:"
      dateValue={legalConfig.termsUpdatedAt}
    >
      <p>
        Welcome to {brand} (hereinafter referred to as &quot;we&quot;, &quot;the
        platform&quot; or &quot;{brand}&quot;). This &quot;User Service
        Agreement&quot; (hereinafter referred to as &quot;this Agreement&quot;)
        is a legal agreement between you and {brand}
        {legalConfig.legalEntityName
          ? `, operated by ${legalConfig.legalEntityName},`
          : ""}{" "}
        regarding access and use of our website, API and related services.
      </p>

      <p>
        <strong className="font-semibold">
          Please read this Agreement carefully before registering, accessing or
          using any of our services. By clicking &quot;Agree&quot;, registering
          an account or actually using the services of this platform, it means
          that you have read, understood and agreed to be bound by this
          Agreement. If you do not agree to any terms of this Agreement, please
          do not use our Services.
        </strong>
      </p>

      <LegalSection title="1. Acceptance of Terms">
        <p>
          This Agreement applies to all users who access or use {brand}{" "}
          services. In addition to this Agreement, your use of certain Services
          may also be subject to other guidelines, rules or privacy policies that
          we may publish from time to time. We reserve the right to modify this
          Agreement when necessary, and the modified Agreement will take effect
          immediately once it is posted on the website. If you continue to use
          the Service after the Agreement is modified, you will be deemed to have
          accepted the modified terms.
        </p>
      </LegalSection>

      <LegalSection title="2. Service description">
        <LegalSubheading>
          2.1 AI large model aggregation and forwarding
        </LegalSubheading>
        <p>
          {brand} is an artificial intelligence large model (LLM) API aggregation
          and forwarding platform. We provide access to a variety of mainstream
          artificial intelligence models (including but not limited to OpenAI,
          Claude, Gemini, and other third-party providers). Our service allows
          users to call these multi-modal models through unified API interface
          standards (such as interfaces compatible with the OpenAI format) to
          generate and process text, images or other content. Third-party models
          remain owned and operated by their respective providers; {brand} does
          not claim ownership of those models.
        </p>

        <LegalSubheading>2.2 Availability and changes to services</LegalSubheading>
        <p>
          Since this service is highly dependent on the interface stability of
          upstream cloud service providers and large model original
          manufacturers, we do not guarantee that all models will be available at
          any time. {brand} reserves the right to add, modify, suspend or offline
          some models or services at any time without prior notice. Models that
          are marked as &quot;experimental&quot; or have been declared obsolete
          by upstream may be removed at any time.
        </p>
      </LegalSection>

      <LegalSection title="3. User qualifications and account security">
        <LegalSubheading>3.1 Age Requirement</LegalSubheading>
        <p>
          You represent that you are at least 18 years of age, or the age of
          majority in your jurisdiction. Minors must use this service under the
          guidance, consent and joint responsibility of their parents or legal
          guardians.{" "}
          <strong className="font-semibold">
            Children aged 13 and under are strictly prohibited from using this
            platform.
          </strong>{" "}
          Due to the unpredictability of the content generated by large models,
          it may produce content that is not suitable for minors, and users are
          responsible for using it at their own risk.
        </p>

        <LegalSubheading>3.2 Account Registration</LegalSubheading>
        <p>
          In order to use {brand}&apos;s core API services, you need to register
          an account. You agree to provide accurate, complete, and up-to-date
          information when registering, and to promptly update the information
          when it changes. If the information you provide is illegal, untrue or
          inaccurate, we have the right to suspend or terminate your account.
        </p>

        <LegalSubheading>3.3 Account and API Key Security</LegalSubheading>
        <p>
          You are solely responsible for the security of your account and
          password.{" "}
          <strong className="font-semibold">
            You must keep your API Key properly and keep it strictly
            confidential.
          </strong>{" "}
          Any call request generated through your API key and the resulting
          billing are deemed to be your own actions, and you bear all
          responsibilities and expenses.
        </p>
        <p>
          If you become aware of any unauthorized use of your account or API key,
          please notify us immediately via the contact information at the end of
          this article.{" "}
          <strong className="font-semibold">
            {brand} does not assume any liability for any financial losses or
            legal consequences caused by the leakage of API keys.
          </strong>
        </p>
      </LegalSection>

      <LegalSection title="4. Service usage specifications">
        <LegalSubheading>4.1 Legal and Compliant Use</LegalSubheading>
        <p>
          You agree to use the {brand} Services only for lawful purposes. You
          must comply with the applicable laws and regulations of your
          country/region, as well as the provisions of this Agreement, when using
          the Service.
        </p>

        <LegalSubheading>4.2 Prohibited Conduct</LegalSubheading>
        <p>When using this service, you must never engage in the following behaviors:</p>
        <LegalList
          items={[
            "Generate, upload, or distribute any illegal, political, terrorist, hate speech, pornographic, violent, defamatory, infringing, or otherwise objectionable content;",
            "Use this service to engage in fraud, send spam, malicious marketing or other behaviors that harm third parties;",
            "Attempt to reverse engineer, decompile, crack or in any way interfere with the normal operation of this platform and the underlying large model;",
            "Use code vulnerabilities, system bugs, etc. to circumvent the billing system or rate limits (Rate Limits);",
            <>
              Use this service to develop a large model aggregation platform that
              directly competes with {brand}.
            </>,
          ]}
        />

        <LegalSubheading>
          4.3 Comply with the terms of the upstream service provider
        </LegalSubheading>
        <p>
          Since {brand} is a forwarding and aggregation platform for models, when
          you call upstream large models such as OpenAI, Anthropic, and Google
          through us, you must also abide by the &quot;Usage Policy&quot; and
          &quot;Terms of Service&quot; of the original manufacturer of the
          corresponding model. If the upstream service provider determines that
          you have violated the regulations due to your usage behavior and bans
          the node or interface we assigned to you, {brand} has the right to
          immediately freeze your account and deduct the illegal income or
          corresponding balance.
        </p>
      </LegalSection>

      <LegalSection title="5. Fees and Payments">
        <LegalSubheading>5.1 Billing Mode</LegalSubheading>
        <p>
          {brand} adopts a &quot;pay-as-you-go&quot; prepaid model. Each valid
          API call you make will deduct the corresponding fee from your account
          balance in real time based on indicators such as the number of tokens
          requested and the number of images generated. For specific billing
          standards and rates, please refer to the real-time announcement on the
          platform&apos;s{" "}
          <Link
            href="/models"
            className="font-medium text-[var(--brand-accent)] underline underline-offset-2 hover:opacity-90"
          >
            Models / pricing page
          </Link>
          .
        </p>

        <LegalSubheading>5.2 Recharge and Refund</LegalSubheading>
        <p>
          You can recharge your balance through the payment methods supported by
          this platform.{" "}
          <strong className="font-semibold">
            In view of the particularity of digital virtual products and API
            services, once the recharge is successful, all account balances do
            not support refunds, withdrawals or transfers, unless the recharge is
            not received due to system failure or expressly stipulated by law.
          </strong>{" "}
          Please make a reasonable assessment of the required amount based on
          your own needs before recharging.
        </p>
      </LegalSection>

      <LegalSection title="6. Privacy and data protection">
        <p>
          We take your privacy and data protection very seriously. {brand} does
          not collect your conversation data or API request content for
          self-training large models. We primarily serve as a channel for data,
          forwarding your request to the designated upstream model service
          provider and returning the results.
        </p>
        <p>
          In order to maintain system security, troubleshoot faults, and verify
          billing, we may temporarily retain necessary request metadata (such as
          request time, IP address, number of consumed Tokens, etc.) in the
          server logs. For specific instructions on the collection and use of
          private data, please see our{" "}
          <Link
            href="/privacy"
            className="font-medium text-[var(--brand-accent)] underline underline-offset-2 hover:opacity-90"
          >
            Privacy Policy
          </Link>
          .
        </p>
      </LegalSection>

      <LegalSection title="7. Intellectual Property Rights">
        <LegalSubheading>7.1 Platform Rights</LegalSubheading>
        <p>
          The Service and its original content, functionality and design are
          protected by intellectual property laws. Use of our services does not
          transfer any intellectual property rights to users or developers.{" "}
          {brand} and its licensors retain all right, title and interest in and
          to the Services.
        </p>

        <LegalSubheading>7.2 Content Rights</LegalSubheading>
        <p>
          The rights related to the prompt words (Prompt) you input into the API
          and the output content (Output) generated by the AI model based on your
          input are owned by you or your end users according to the policies of
          the upstream model original manufacturer and applicable laws. {brand}{" "}
          does not make any claims about the copyright ownership of the content
          you generate.
        </p>
      </LegalSection>

      <LegalSection title="8. Disclaimer and Limitation of Liability">
        <LegalSubheading>8.1 PROVIDED &quot;AS IS&quot;</LegalSubheading>
        <p>
          {brand} and its aggregated underlying large model services are provided
          on an &quot;As is&quot; and &quot;As available&quot; basis. We make no
          warranty, express or implied, that the Service will be error-free,
          absolutely secure, uninterrupted, or meet your specific expectations.
        </p>

        <LegalSubheading>8.2 Content Disclaimer</LegalSubheading>
        <p>
          Due to the inherent technical characteristics of large artificial
          intelligence models, the results returned by the API may contain
          inaccuracies, hallucinations, outdated or objectionable content. You
          should independently verify the accuracy of the generated content, and{" "}
          {brand} is not legally responsible for any direct or indirect losses
          caused by your reliance on or use of these outputs.
        </p>

        <LegalSubheading>8.3 Limitation of Liability</LegalSubheading>
        <p>
          To the maximum extent permitted by applicable law, {brand} shall not be
          liable for any indirect, incidental, special or punitive damages
          (including lost profits, loss of data, etc.) arising out of the use of
          or inability to use the Service, regardless of legal theory (contract,
          tort or otherwise). In any event, {brand}&apos;s maximum liability to
          you shall not exceed the total amount of API fees actually paid by you
          to us in the twelve months preceding the event giving rise to the
          claim.
        </p>
      </LegalSection>

      <LegalSection title="9. Termination of service">
        <LegalSubheading>9.1 Termination by User</LegalSubheading>
        <p>
          You can stop using our services at any time. If you wish to delete your
          account, please follow the instructions in our website&apos;s{" "}
          <Link
            href="/privacy"
            className="font-medium text-[var(--brand-accent)] underline underline-offset-2 hover:opacity-90"
          >
            Privacy Policy
          </Link>
          .
        </p>

        <LegalSubheading>9.2 Termination by Platform</LegalSubheading>
        <p>
          If you violate any terms of this Agreement (especially Prohibited
          Conduct in 4.2), {brand} has the right to immediately suspend or
          permanently terminate your account and API access without prior notice,
          and without refunding any fees remaining in the account.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing Law and Dispute Resolution">
        <p>
          The formation, execution and interpretation of this Agreement and the
          resolution of disputes shall be governed by applicable local and
          international Internet-related laws and practices
          {legalConfig.jurisdiction
            ? `, including the laws of ${legalConfig.jurisdiction}`
            : ""}
          . If any dispute arises between the two parties regarding the content
          of this Agreement or its execution, the parties shall try their best to
          resolve it through friendly negotiation; if negotiation fails, either
          party may file a lawsuit with the court with jurisdiction where the{" "}
          {brand} operator
          {legalConfig.legalEntityName
            ? ` (${legalConfig.legalEntityName})`
            : ""}{" "}
          is located.
        </p>
      </LegalSection>

      <LegalSection title="11. Contact us">
        <p>
          If you have any questions, comments or need to report violations
          regarding this User Service Agreement, please feel free to contact us
          via the following email address:
        </p>
        <p>
          <strong className="font-semibold">Service and support email:</strong>{" "}
          <a
            href={legalMailto.support}
            className="font-medium text-[var(--brand-accent)] underline underline-offset-2 hover:opacity-90"
          >
            {legalConfig.supportEmail}
          </a>
        </p>
        {legalConfig.registeredAddress ? (
          <p className="text-[#667085]">
            {legalConfig.legalEntityName}
            {legalConfig.legalEntityName ? " · " : ""}
            {legalConfig.registeredAddress}
          </p>
        ) : null}
        <hr className="my-8 border-[#eaecf0]" />
        <p>
          <strong className="font-semibold">
            Thank you for using {brand}. Good luck building the next great AI
            application!
          </strong>
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
